app:
  name: spring-boot-app
  description: Example Spring Boot Application

  servers:
    - server1
    - server2
    - server3

  environments:
    dev:
      name: Developement Enviroment
      url: https://dev.example.com

    prod:
      name: Prod Enviroment
      url: http://prod.example.com



